name: image_picker_plus_for_web
description: Web platform implementation of image_picker_plus
repository: https://github.com/WutangNailao/image_picker_plus/tree/main/image_picker_plus_for_web
issue_tracker: https://github.com/WutangNailao/image_picker_plus/issues
version: 0.0.2

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

resolution: workspace

flutter:
  plugin:
    implements: image_picker_plus
    platforms:
      web:
        pluginClass: ImagePickerPlugin
        fileName: image_picker_plus_for_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image_picker_plus_platform_interface: ^0.0.3
  mime: ">=1.0.4 <3.0.0"
  web: ">=0.5.1 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - camera
  - image-picker
  - files
  - file-selection
