name: image_picker_plus_linux
description: Linux platform implementation of image_picker_plus
repository: https://github.com/WutangNailao/image_picker_plus
issue_tracker: https://github.com/WutangNailao/image_picker_plus/issues
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

flutter:
  plugin:
    implements: image_picker_plus
    platforms:
      linux:
        dartPluginClass: ImagePickerLinux

dependencies:
  file_selector_linux: ^0.9.1+3
  file_selector_platform_interface: ^2.2.0
  flutter:
    sdk: flutter
  image_picker_plus_platform_interface: ^0.0.1

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

topics:
  - image-picker
  - files
  - file-selection
