name: image_picker_pluz
description: Flutter plugin for selecting images from the Android and iOS image
  library, and taking new pictures with the camera.
repository: https://github.com/WutangNailao/image_picker_plus/tree/main/image_picker_pluz
issue_tracker: https://github.com/WutangNailao/image_picker_plus/issues
version: 0.0.3

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: image_picker_plus_android
      ios:
        default_package: image_picker_plus_ios
      linux:
        default_package: image_picker_plus_linux
      macos:
        default_package: image_picker_plus_macos
      web:
        default_package: image_picker_plus_for_web
      windows:
        default_package: image_picker_plus_windows

dependencies:
  flutter:
    sdk: flutter
  image_picker_plus_android: ^0.0.4
  image_picker_plus_for_web: ^0.0.2
  image_picker_plus_ios: ^0.0.6
  image_picker_plus_linux: ^0.0.2
  image_picker_plus_macos: ^0.0.2
  image_picker_plus_platform_interface: ^0.0.3
  image_picker_plus_windows: ^0.0.2
dev_dependencies:
  build_runner: ^2.1.10
  cross_file: ^0.3.1+1 # Mockito generates a direct include.
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.7

topics:
  - camera
  - image-picker
  - files
  - file-selection
