name: image_picker_plus_ios
description: iOS implementation of the image_picker_plus plugin.
repository: https://github.com/WutangNailao/image_picker_plus
issue_tracker: https://github.com/WutangNailao/image_picker_plus/issues
version: 0.0.1

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

flutter:
  plugin:
    implements: image_picker_plus
    platforms:
      ios:
        dartPluginClass: ImagePickerIOS
        pluginClass: FLTImagePickerPlugin

dependencies:
  flutter:
    sdk: flutter
  image_picker_plus_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^26.1.0

topics:
  - camera
  - image-picker
  - files
  - file-selection
