name: image_picker_plus_android
description: Android implementation of the image_picker_plus plugin.
repository: https://github.com/WutangNailao/image_picker_plus/image_picker_plus_android
issue_tracker: https://github.com/WutangNailao/image_picker_plus/issues
version: 0.0.2

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

flutter:
  plugin:
    implements: image_picker_plus
    platforms:
      android:
        package: io.flutter.plugins.imagepicker
        pluginClass: ImagePickerPlugin
        dartPluginClass: ImagePickerAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  image_picker_plus_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ^26.1.0

topics:
  - camera
  - image-picker
  - files
  - file-selection
