name: image_picker_plus_platform_interface
description: A common platform interface for the image_picker_plus plugin.
repository: https://github.com/WutangNailao/image_picker_plus/image_picker_plus_platform_interface
issue_tracker: https://github.com/WutangNailao/image_picker_plus/issues
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.0.2

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  cross_file: ^0.3.5+1
  flutter:
    sdk: flutter
  http: ">=0.13.0 <2.0.0"
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  web: ^1.1.0

topics:
  - image-picker
  - files
  - file-selection
